INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('1', 'Afganistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('2', 'Albania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('3', 'Alemania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('4', 'Andorra');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('5', 'Angola');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('6', 'Antigua y Barbuda');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('7', 'Arabia Saudita');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('8', 'Argelia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('9', 'Argentina');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('10', 'Armenia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('11', 'Australia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('12', 'Austria');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('13', 'Azerbaiyán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('14', 'Bahamas');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('15', 'Bangladés');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('16', 'Barbados');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('17', 'Baréin');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('18', 'Bélgica');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('19', 'Belice');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('20', 'Benín');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('21', 'Bielorrusia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('22', 'Birmania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('23', 'Bolivia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('24', 'Bosnia-Herzegovina');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('25', 'Botsuana');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('26', 'Brasil');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('27', 'Brunéi');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('28', 'Bulgaria');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('29', 'Burkina Faso');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('30', 'Burundi');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('31', 'Bután');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('32', 'Cabo Verde');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('33', 'Camboya');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('34', 'Camerún');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('35', 'Canadá');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('36', 'Catar');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('37', 'Chad');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('38', 'Chile');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('39', 'China');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('40', 'Chipre');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('41', 'Colombia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('42', 'Comoras');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('43', 'Congo');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('44', 'Corea del Norte');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('45', 'Corea del Sur');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('46', 'Costa de Marfil');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('47', 'Costa Rica');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('48', 'Croacia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('49', 'Cuba');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('50', 'Dinamarca');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('51', 'Dominica');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('52', 'Ecuador');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('53', 'Egipto');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('54', 'El Salvador');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('55', 'Emiratos Árabes Unidos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('56', 'Eritrea');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('57', 'Eslovaquia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('58', 'Eslovenia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('59', 'España');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('60', 'Estados Unidos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('61', 'Estonia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('62', 'Etiopía');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('63', 'Filipinas');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('64', 'Finlandia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('65', 'Fiyi');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('66', 'Francia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('67', 'Gabón');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('68', 'Gambia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('69', 'Georgia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('70', 'Ghana');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('71', 'Granada');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('72', 'Grecia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('73', 'Guatemala');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('74', 'Guinea');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('75', 'Guinea Ecuatorial');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('76', 'Guinea-Bisáu');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('77', 'Guyana');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('78', 'Haití');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('79', 'Honduras');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('80', 'Hungría');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('81', 'India');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('82', 'Indonesia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('83', 'Irak');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('84', 'Irán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('85', 'Irlanda');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('86', 'Islandia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('87', 'Islas Marshall');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('88', 'Islas Salomón');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('89', 'Israel');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('90', 'Italia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('91', 'Jamaica');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('92', 'Japón');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('93', 'Jordania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('94', 'Kazajistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('95', 'Kenia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('96', 'Kirguistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('97', 'Kiribati');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('98', 'Kosovo');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('99', 'Kuwait');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('100', 'Laos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('101', 'Lesoto');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('102', 'Letonia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('103', 'Líbano');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('104', 'Liberia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('105', 'Libia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('106', 'Liechtenstein');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('107', 'Lituania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('108', 'Luxemburgo');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('109', 'Macedonia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('110', 'Madagascar');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('111', 'Malasia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('112', 'Malaui');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('113', 'Maldivas');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('114', 'Malí');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('115', 'Malta');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('116', 'Marruecos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('117', 'Mauricio');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('118', 'Mauritania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('119', 'México');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('120', 'Micronesia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('121', 'Moldavia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('122', 'Mónaco');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('123', 'Mongolia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('124', 'Montenegro');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('125', 'Mozambique');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('126', 'Namibia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('127', 'Nauru');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('128', 'Nepal');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('129', 'Nicaragua');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('130', 'Níger');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('131', 'Nigeria');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('132', 'Noruega');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('133', 'Nueva Zelanda');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('134', 'Omán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('135', 'Países Bajos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('136', 'Pakistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('137', 'Palaos');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('138', 'Palestina');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('139', 'Panamá');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('140', 'Papúa Nueva Guinea');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('141', 'Paraguay');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('142', 'Perú');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('143', 'Polonia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('144', 'Portugal');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('145', 'Reino Unido');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('146', 'República Centroafricana');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('147', 'República Checa');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('148', 'República Democrática del Congo');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('149', 'República Dominicana');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('150', 'Ruanda');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('151', 'Rumania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('152', 'Rusia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('153', 'Samoa');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('154', 'San Cristóbal y Nieves');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('155', 'San Marino');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('156', 'San Vicente y las Granadinas');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('157', 'Santa Lucía');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('158', 'Santo Tomé y Príncipe');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('159', 'Senegal');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('160', 'Serbia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('161', 'Seychelles');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('162', 'Sierra Leona');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('163', 'Singapur');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('164', 'Siria');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('165', 'Somalia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('166', 'Sri Lanka');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('167', 'Suazilandia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('168', 'Sudáfrica');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('169', 'Sudán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('170', 'Sudán del Sur');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('171', 'Suecia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('172', 'Suiza');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('173', 'Surinam');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('174', 'Tailandia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('175', 'Taiwán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('176', 'Tanzania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('177', 'Tayikistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('178', 'Timor Oriental');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('179', 'Togo');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('180', 'Tonga');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('181', 'Trinidad y Tobago');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('182', 'Túnez');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('183', 'Turkmenistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('184', 'Turquía');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('185', 'Tuvalu');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('186', 'Ucrania');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('187', 'Uganda');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('188', 'Uruguay');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('189', 'Uzbekistán');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('190', 'Vanuatu');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('191', 'Vaticano');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('192', 'Venezuela');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('193', 'Vietnam');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('194', 'Yemen');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('195', 'Yibuti');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('196', 'Zambia');
INSERT INTO `QueLeo`.`Pais` (`Id_Pais`, `Nombre`) VALUES ('197', 'Zimbabue');

INSERT INTO `QueLeo`.`Estado_Civil` (`Id_Estado`, `Nombre`) VALUES ('1', 'Soltero/a');
INSERT INTO `QueLeo`.`Estado_Civil` (`Id_Estado`, `Nombre`) VALUES ('2', 'Unión Libre');
INSERT INTO `QueLeo`.`Estado_Civil` (`Id_Estado`, `Nombre`) VALUES ('3', 'Casado/a');
INSERT INTO `QueLeo`.`Estado_Civil` (`Id_Estado`, `Nombre`) VALUES ('4', 'Divorciado/a');
INSERT INTO `QueLeo`.`Estado_Civil` (`Id_Estado`, `Nombre`) VALUES ('5', 'Viudo/a');


INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('1', 'Ninguno');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('2', 'Primaria');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('3', 'Secundaria');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('4', 'Tecnico');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('5', 'Tecnologo');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('6', 'Profesional');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('7', 'Especialización');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('8', 'Maestría');
INSERT INTO `QueLeo`.`Nivel_Educativo` (`Id_Nivel`, `Nombre`) VALUES ('9', 'Doctorado');


INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('1', 'Policial (o Thriller)', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('2', 'Romántica', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('3', 'Aventura', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('4', 'Terror', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('5', 'Ficcion / Realidad', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('6', 'Ciencia Ficción', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('7', 'Investigación', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('8', 'Biográfica', '');
INSERT INTO `QueLeo`.`Genero` (`Id_Genero`, `Nombre`, `Descripcion`) VALUES ('9', 'Infantil', '');


INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('1', 'Alimentos / Cocina', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('2', 'Arte', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('3', 'Astronomía', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('4', 'Cambio Climático', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('5', 'Ciencia', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('6', 'Civilización', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('7', 'Corrupción', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('8', 'Cultura', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('9', 'Derechos Humanos', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('10', 'Educación', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('11', 'Energía', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('12', 'Familia', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('13', 'Farándula', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('14', 'Finanzas / Economía', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('15', 'Futuro', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('16', 'Guerra', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('17', 'Historia', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('18', 'Lenguas', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('19', 'Leyes', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('20', 'Medio Ambiente', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('21', 'Moda', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('22', 'Paz', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('23', 'Política', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('24', 'Redes Sociales', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('25', 'Religión', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('26', 'Salud', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('27', 'Sexo', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('28', 'Tecnología', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('29', 'Vivienda', '');
INSERT INTO `QueLeo`.`Tema_Interes` (`Id_Tema`, `Nombre`, `Descripcion`) VALUES ('30', 'Otros', '');